# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gitea.v1 import messages_pb2 as gitea_dot_v1_dot_messages__pb2


class GiteaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Gitea = channel.unary_unary(
                '/gitea.v1.GiteaService/Gitea',
                request_serializer=gitea_dot_v1_dot_messages__pb2.GiteaRequest.SerializeToString,
                response_deserializer=gitea_dot_v1_dot_messages__pb2.GiteaResponse.FromString,
                )
        self.Introduce = channel.unary_stream(
                '/gitea.v1.GiteaService/Introduce',
                request_serializer=gitea_dot_v1_dot_messages__pb2.IntroduceRequest.SerializeToString,
                response_deserializer=gitea_dot_v1_dot_messages__pb2.IntroduceResponse.FromString,
                )


class GiteaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Gitea(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Introduce(self, request, context):
        """Introduce is a server-streaming request demo.  This method allows for a single request that will return a series
        of responses
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GiteaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Gitea': grpc.unary_unary_rpc_method_handler(
                    servicer.Gitea,
                    request_deserializer=gitea_dot_v1_dot_messages__pb2.GiteaRequest.FromString,
                    response_serializer=gitea_dot_v1_dot_messages__pb2.GiteaResponse.SerializeToString,
            ),
            'Introduce': grpc.unary_stream_rpc_method_handler(
                    servicer.Introduce,
                    request_deserializer=gitea_dot_v1_dot_messages__pb2.IntroduceRequest.FromString,
                    response_serializer=gitea_dot_v1_dot_messages__pb2.IntroduceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gitea.v1.GiteaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GiteaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Gitea(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gitea.v1.GiteaService/Gitea',
            gitea_dot_v1_dot_messages__pb2.GiteaRequest.SerializeToString,
            gitea_dot_v1_dot_messages__pb2.GiteaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Introduce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/gitea.v1.GiteaService/Introduce',
            gitea_dot_v1_dot_messages__pb2.IntroduceRequest.SerializeToString,
            gitea_dot_v1_dot_messages__pb2.IntroduceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
